version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/instance/ats.db
    networks:
      - ats-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - ats-network

networks:
  ats-network:
    driver: bridge