services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/instance/ats.db
    command: >
      sh -c "
        if [ ! -f /app/instance/ats.db ]; then
          echo 'Database does not exist, creating a new one...'
          python -c 'from api import db; db.create_all()'
        fi
        python api.py
      "

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

volumes:
  instance:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/instance
